In [23]:
import numpy as np
from math import sqrt

## Question 1:
Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 * C * D)/H]
Following are the fixed values of C and H:
C is 50. H is 30.
D is the variable whose values should be input to your program in a comma-separated
sequence.
Example
Let us assume the following comma separated input sequence is given to the program:
100,150,180
The output of the program should be:
18,22,24

In [21]:
C = 50
H = 30
D = list(input().split(','))
m = []
for i in D:
    Q = int(sqrt(2*C*int(i)/H))
    print(Q,end=',')
          
         

100,150,180
18,22,24,

## Question 2:
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The
element value in the i-th row and j-th column of the array should be i*j.
Note: i=0,1.., X-1; j=0,1,¡Y-1.
Example
Suppose the following inputs are given to the program:
3,5
Then, the output of the program should be:
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [52]:
def question2():
    x = int(input('Enter the No of Rows:'))
    y = int(input('Enter the No of Columns:')) 
    c = np.array([[0] * y] * x)
    for i in range(x):
        for j in range(y):
            c[i][j]= i*j
    print(c)        
question2()            

Enter the No of Rows:3
Enter the No of Columns:5
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


## Question 3:
Write a program that accepts a comma separated sequence of words as input and prints the
words in a comma-separated sequence after sorting them alphabetically.
Suppose the following input is supplied to the program:
without,hello,bag,world
Then, the output should be:
bag,hello,without,world

In [54]:
def words():
    word_list = list(input().split(','))
    return sorted(word_list,reverse=False)
words()

cat,rat,mat,pet


['cat', 'mat', 'pet', 'rat']

## Question 4:
Write a program that accepts a sequence of whitespace separated words as input and prints
the words after removing all duplicate words and sorting them alphanumerically.
Suppose the following input is supplied to the program:
hello world and practice makes perfect and hello world again
Then, the output should be:
again and hello makes perfect practice world

In [59]:
def alpha_words():
    word_list = list(input().split(' '))
    return list(sorted(set(word_list)))
alpha_words()

hello world and practice makes perfect and hello world again


['again', 'and', 'hello', 'makes', 'perfect', 'practice', 'world']

## Question 5:
Write a program that accepts a sentence and calculate the number of letters and digits.
Suppose the following input is supplied to the program:
hello world! 123
Then, the output should be:
LETTERS 10

DIGITS 3

In [69]:
def countLetterAndDigits():
    in_string = input("Enter the Input String: ")
    lettersList = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
    digitsList = '0123456789'
    letters = 0
    digits = 0
    for ele in in_string:
        if ele in lettersList:
            letters += 1
        if ele in digitsList:
            digits += 1
    print(f'LETTERS {letters} \nDIGITS {digits}')
        
countLetterAndDigits()

Enter the Input String: hello world! 123
LETTERS 10 
DIGITS 3


## Question 6:
A website requires the users to input username and password to register. Write a program to
check the validity of password input by users.
Following are the criteria for checking the password:
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12
Your program should accept a sequence of comma separated passwords and will check them
according to the above criteria. Passwords that match the criteria are to be printed, each
separated by a comma.
Example
If the following passwords are given as input to the program:
ABd1234@1,a F1#,2w3E*,2We3345
Then, the output of the program should be:
ABd1234@1

In [70]:
def checkPassword():
    in_string = input("Enter the Input String: ")
    small_list = "abcdefghijklmnopqrstuvwxyz"
    cap_list = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    num_list = "0123456789"
    special_list = "$#@"
    for ele in in_string.split(","):
        if len(ele) <= 12 and len(ele) >=6 :
            if any(i.isupper() for i in ele):
                if any(i.islower() for i in ele):
                    if any(i for i in ele if i in special_list):
                        print(ele)
                               
checkPassword() 

Enter the Input String: ABd1234@1,a F1#,2w3E*,2We3345
ABd1234@1
